export const SUBJECT_REVISION_PROMPTS = [
        "Please mark that the subject is offered for sale in the subject section.",
        "Please add the borrower's middle initial (M) to the report.",
        "The unit number is missing from the subject’s address; please update it so it reflects: 5727 Kilbury Lane Unit 123D Hilliard, OH 43026",
        "The subject's street name should reflect as \"River Bend\" (two words); please revise.",
        "Please revise the subject's street suffix from Cir to Dr.",
        "The lender name is incomplete, please update so it reflects: aura capital funding mangement LLC",
        "Please add the street suffix ‘Dr’ in the lender address.",
        "Please revise the subject’s property address to match the order form: 3437-3439 Viking St",
        "Please add ‘Inc’ at the end of the lender/client name: OCMBC Inc.",
        "Please revise the spelling of the lender name:",
        "Please revise the borrower's last name to ‘Arnett’.",
        "Please revise the spelling of the lender's city: Tucson.",
        "Please revise the state in the lender's address: PA",
        "Please remove ‘Inc’ from the lender/client name so it reflects as JMAC Lending.",
        "Please add ‘W’ direction in the subject property address so it reflects: 5727 Kilbury Lane W Unit 123D Hilliard, OH 43026",
        "Please revise the lender/client address city name to match the order form:",
        "Please revise the borrower name to match the order form:",
        "Please revise the spelling of the borrower’s first name:",
        "Please have the ‘Legal Description’ noted in the report.",
        "The ‘Legal Description’ is noted as “see attached addendum”; however, the legal description is not provided in the addendum. Please revise.",
        "Please have the ‘Assessor's Parcel #’ noted in the subject section.",
        "Please revise the borrower name to only Adam Gleve.",
        "Please have the ‘Neighborhood Name’ noted in the subject section.",
        "The occupancy is marked as ‘Owner’; however, the interior photos indicate the property as vacant. Please verify/revise.",
        "The occupancy is marked as ‘Vacant’; however, the interior photos indicate the property as occupied. Please verify/revise.",
        "Zoning states PUD, but PUD box is not checked. Please update or comment confirming if the subject is a PUD.",
        "The subject section indicates the property is in PUD; however, the PUD Information section on page 3 is incomplete. Please revise.",
        "In the subject section, the HOA amount is noted; however, the ‘per year’ or ‘per month’ is not marked. Please revise.",
        "Please uncheck the PUD box in the subject section.",
        "The PUD box is marked in the subject section; however, the HOA amount is noted as 0. Please verify.",
        "The subject section indicates the property is not located in PUD; however, the PUD Information section on page 6 is completed. Please revise.",
        "Please remove ‘Trust’ from the lender/client name so it reflects as BPL Mortgage, LLC.",
        "Please have the appropriate box marked for ‘Property Rights Appraised’ in the subject section.",
        "Please revise the lender/client name to match the order form: NQM Funding, LLC",
        "Please include an owner of public record on page 1.",
        "Please revise the suite number in the lender/client address: Suite 400.",
        "Please have the offering price noted for ‘Report data source(s) used, offering price(s), and date(s)’ in the subject section.",
        "Please refer to the attached legal description in the Legal Description field on page 1.",
        "Please have the appropriate checkbox marked for ‘Is the subject property currently offered for sale, or has it been offered for sale in the twelve months prior to the effective date of this appraisal?’ in the subject section.",
        "This is an investment property; please revise the occupancy to tenant or vacant.",
        "Please revise the lender/client address on the signature card:",
        "Subject section: Please revise the checkbox marked for question ‘Is the subject property currently offered for sale, or has it been offered for sale in the twelve months prior to the effective date of this appraisal?’.",
        "Please revise the checkbox for assignment type to refinance transaction.",
        "Please revise the checkbox for Property Rights Appraised to fee simple."
];

export const CONTRACT_REVISION_PROMPTS = [
    "The ‘Contract Price’ noted in the report does not match with the purchase agreement; please revise.",
    "The ‘Date of Contract’ noted in the contract section does not match with the purchase agreement; please revise.",
    "The report shows the ‘Contract Price’ as $295,000; however, the purchase agreement shows the contract price as $280,000. Please verify.",
    "The question is, ‘Is there any financial assistance (loan charges, sale concessions, gift or down payment assistance, etc.) to be paid by any party on behalf of the borrower?’ is marked on YES; however, the concession amount is noted as 0, please revise.",
    "The report shows the concession amount as $5000; however, the purchase agreement shows the concession as $8000. Please verify.",
    "Please provide the transaction type on page #1 of the appraisal report in the contract section, whether it is arm's length or non-arm's length."
];

export const NEIGHBORHOOD_REVISION_PROMPTS = [
    "Neighborhood section: The predominant price noted under ‘One-Unit Housing’ does not fall between their Low to High price range, please revise.",
    "Neighborhood Section: It appears the low and high price range is interchanged under 'One-Unit Housing'.",
    "Neighborhood section: The predominant age noted under ‘One-Unit Housing’ does not fall between their Low to High age range, please revise.",
    "Please have the low, high and predominant value noted under 'One-Unit Housing’ of improvements section.",
    "Neighborhood section: The predominant value does not fall within the low to high price.",
    "Please provide appropriate neighborhood boundaries of all directions in the Neighborhood section.",
    "Please revise the ‘Present Land Use’ percentage as it should be 100%.",
    "Please comment on 10% other land usage.",
    "Appraised value is lower than Predominant value. Appraiser to comment whether it is an under improvement and if there is any impact on the value and marketability of the subject property.",
    "Appraised value is higher than Predominant value. Appraiser to comment whether it is an over improvement and if there is any impact on the value and marketability of the subject property.",
    "The appraised value is lower than predominant value however the comment on page# 13 says \"...........\", please revise.",
    "The appraised value is higher than predominant value however the comment on page# 13 says \"...........\", please revise.",
    "The comment in the Neighborhood section reads \"The level of maintenance and the condition of the houses are average.\", Please advise.",
    "The North boundary is missing from the ‘Neighborhood Boundaries’, please provide",
    "Please provide the south side boundary of the neighborhood and revise the north boundary which is described twice."
];

export const SITE_REVISION_PROMPTS = [
    "On page 1, please check a box for \"Are the utilities and/or off-site improvements typical for the market area?\"",
    "The ‘Zoning Compliance’ is marked on ‘Legal Nonconforming (Grandfathered Use)’; please comment if the subject can be rebuilt if destroyed.",
    "The ‘Zoning Compliance’ is marked as ‘No Zoning’; please comment if the subject can be rebuilt if destroyed.",
    "The question is, ‘Is the highest and best use of the subject property as improved (or as proposed per plans and specifications) the present use?’ is marked as No; however, the description is not provided; please revise/describe.",
    "Photos indicate the subject has an ‘Alley’; however, the ‘Alley’ box is not marked in the Site section. Please revise.",
    "The subject has septic; please comment if it is typical or not.",
    "Please address if the distance between well and septic meets HUD requirements",
    "Site section: The ‘Sanitary Sewer’ is marked as public; however, it is noted as septic. Please revise.",
    "‘FEMA Special Flood Hazard Area' marked as ‘NO’ ; however, FEMA Flood Zone is AE; please revise.",
    "Please revise the checkbox marked for the question ‘Are there any adverse site conditions or external factors (easements, encroachments, environmental conditions, land uses, etc.)?’ in the site section, as it does not support the comment noted for the same.",
    "Please mention ac. or sf for site area in the site section."
];

export const IMPROVEMENTS_REVISION_PROMPTS = [
    "Photos and sketches indicate the subject has an ADU; however, the ‘One with Accessory Unit’ box is not marked in the Improvements section; please revise.",
    "The guest house does not have a kitchen; however, it is marked as an accessory unit in the General Description. Please revise, as the guest house does not appear to meet the qualifications of an ADU.",
    "The subject’s ‘Design (Style)’ noted in the sales grid does not match with the Improvements section; please revise.",
    "Improvements section: Under general description, the checkbox is marked on ‘Proposed’; however, photos indicate the under-construction property; please revise.",
    "Please have the condition noted for ‘Exterior Walls’ under the exterior description of the Improvements section.",
    "Please have the condition noted for ‘Walls’ under the interior description of the Improvements section.",
    "Photos indicate the subject has an attic; however, the attic box is not marked in the Improvements section; please revise.",
    "The subject’s ‘Heating/Cooling’ noted in the sales grid does not match with the improvements section; please revise.",
    "The improvements section shows the subject has ‘Central Air Conditioning’ for cooling; however, the sales grid shows No CAC. Please revise.",
    "Please reflect the GLA as a whole number.",
    "The improvements section shows the subject has 2 detached garages; however, the sales grid and sketch indicate the subject has 2 attached garages. Please revise.",
    "Per photos, the subject appears to be detached property; however, in the Improvements section, the checkbox is marked on ‘Att.’ Please revise.",
    "Improvements section: Porch box is marked, however noted as ‘None’; please revise.",
    "Photos and sketches do not indicate the ADU; however, the ‘One with Accessory Unit’ box is marked in the Improvements section; please revise.",
    "Please revise the checkbox marked for the question ‘Are there any physical deficiencies or adverse conditions that affect the livability, soundness, or structural integrity of the property?’ in the improvements section as it does not support the comment noted for the same.",
    "The Front Unit #1 GLA area does not match with the sketch.",
    "In the improvement section, the pool box is marked, however noted as “none”; please revise.",
    "Photos indicate the subject has a ‘crawl space’; however, the crawl space box is not marked in the Improvements section; please revise.",
    "On the sales grid, please reflect the GLA as a whole number. The report currently reflects \"1,555.8.\"",
    "Please include the sketch in the report.",
    "The 3rd and 4th bathroom photo provided on page# 23 appears to be duplicate, please revise Please provide all bedroom photos in the report.",
    "Please label the 1/2 bath on the sketch."
];

export const SALES_GRID_REVISION_PROMPTS = [
    "Sales grid:Please provide a low price value for ‘comparable sales in the subject neighborhood within the past twelve months’ towards the top of the sales grid.",
    "Please have the appropriate data noted towards the top of the sales grid, i.e., for ‘comparable properties currently offered for sale’ and ‘comparable sales in the subject neighborhood within the past twelve.’.",
    "Please have the count noted for ‘comparable properties currently offered for sale in the subject neighborhood’ towards the top of the sales grid.",
    "Please have the count noted for ‘comparable sales in the subject neighborhood within the past twelve months’ towards the top of the sales grid.",
    "Comp 3's settled date reflects 'after' the effective date of the report. Please update accordingly.",
    "Please revise the price range noted for ‘comparable properties currently offered for sale…’ towards the top of the sales grid, as it should be low to high.",
    "Comp #1 is noted as a listing; however, a minimum of 3 closed sales are required. Please update the report to show closed sales for the first 3 comps.",
    "Please revise the actual age of the subject in the sales grid: 104",
    "Please have the appropriate ‘Verification Source(s)’ noted for comp #3.",
    "Please revise the ‘Date of Sale/Time’ noted for comp #1, as its sale date is before its contract date.",
    "Please provide a ‘View’ adjustment for comp #1 or comment on why it was not warranted as compared to the subject.",
    "Please correct the \"Year\" of the \"Contract date\" for Comp 4, as it shows a future date.",
    "3560 Avenue 400",
    "The ‘actual age’ adjustment made for comp #6 goes in the wrong direction; please revise.",
    "The GLA adjustment made for comp #5 seems to be inconsistent with the other comps; please revise.",
    "The Bath adjustment made for comp #5 seems to be inconsistent with the other comps; please revise.",
    "Please revise the checkbox marked for ‘did or did not reveal any prior sales or transfers of the subject property for the three years…’ in the prior sale history section.",
    "The sales grid indicates the subject has a porch; however, the porch box is not marked in the Improvements section; please revise.",
    "The improvements section shows the subject has a porch; however, it is not mentioned in the sales grid; please revise.",
    "Please have the 'Proximity to Subject' noted for comp #3 and 4 on the sales grid.",
    "Please revise the checkbox marked for ‘did or did not reveal any prior sales or transfers of the comparable sales…’ in the prior sale history section.",
    "The subject’s final value does not match with the ‘Indicated Value by Sales Comparison Approach’, please revise or comment.",
    "The Final value and ‘Indicated Value by Sales Comparison Approach’ is not bracketed by the adjusted sales price of comparables; please revise.",
    "Please provide bathroom adjustment for comp# 2 or comment why it was not warranted as compare to the subject.",
    "Please revise or comment why bathroom adjustment was warranted for comp# 2 as compare to the subject.",
    "Please provide a condition adjustment for comps #1-3 or comment on why it was not warranted.",
    "Please review the 'Garage/carport' adjustment made for all comps, as it seems inconsistent with each other.",
    "Please revise the low value noted for ‘comparable properties currently offered for sale in the subject neighborhood’ on the top of the sales grid as it currently reads “289,900,268,83.",
    "The basement room details on the sales grid do not match with the sketch. Please revise to match.",
    "The basement room details on the sales grid and improvement section do not match with the sketch and photos. Please revise to match.",
    "Page 1 indicates a 6-car detached garage; however, the grid and sketch indicate a 10-car detached garage. Please revise to match.",
    "The subject is leasehold; however, only one comp of leasehold is used in the sale grid. Please include leasehold comps or address why none could be provided.",
    "It appears the ADU details are included in the main unit details (bed, bath, and GLA). ADU details should not be included with the main unit's details and should only be included as a separate line item in the grid; please revise.",
    "Sales grid: Please revise the \"Contract Date\" line item for the subject, as it includes \"In Ground.\".",
    "Please revise the adjusted sales price of comparables on page 10 so it corresponds with the sales grid.",
    "Please review the \"Pool\" line item for the comps, as dates are included. If pool adjustments are warranted, please include them.",
    "Please revise the \"Fireplace\" line item for Comp 3, as it includes \"Pool.\"",
    "The improvements section shows the subject has 1 fireplace; however, the sales grid indicates the subject has 2 fireplaces. Please revise.",
    "Please address the increase in value since the subject's prior sale",
    "Please include descriptions for the last 2 line items and complete the fields accordingly for Comps 1 and 4."
];

export const RECONCILIATION_REVISION_PROMPTS = [
    "Please revise the checkbox in the reconciliation section to ‘subject to completion per plans and specifications..’ instead of ‘subject to the following repairs…’.",
    "Please revise or comment as to why the report made subject to completion per plans.",
    "Please update the year in the effective date to 2025."
];

export const COST_APPROACH_REVISION_PROMPTS = [
    "Please include the ‘OPINION OF SITE VALUE’ in the report.",
    "Please include the ‘Estimated Remaining Economic Life’ in the report.",
    "Please revise the conflicting comment noted on page# 4 which reads “Estimated remaining economic life: 59 Years.” However the same section also comment noted as ‘remaining economic life of 60 years’",
    "Please develop the cost approach section of the report per client requirement.",
    "Fannie Mae requires appraisers to complete the cost approach for all manufactured homes. Please include the cost approach.",
    "Please have the appropriate checkbox marked in the cost approach section. (i.e. REPRODUCTION OR REPLACEMENT COST NEW)",
    "For BPL only: This client requires the Cost Approach to be completed. Even if this approach is not weighted in determining value, it must be completed."
];

export const CERTIFICATION_REVISION_PROMPTS = [
    "Signature page:",
    "Please sign the report.",
    "Please provide an updated signature date in the report.",
    "Please revise the ‘Expiration Date of Certification or License’ on the signature card to match the appraiser’s license copy.",
    "Please revise the ‘Date of Signature’ as it is prior to the ‘Effective Date of Appraisal.’.",
    "The appraiser’s license number noted in the signature card does not match with the license copy; please revise.",
    "For update files: Please revise the AMC in the signature card back to Fastapp Appraisal Management Company.",
    "Please include the AMC name in the signature card: Coast to Coast Appraisal Services, Inc.",
    "Please revise the AMC name in the signature card: Fastapp Appraisal Management Company",
    "Please attach the active E&O insurance copy in the report, as the one in the report is expired.",
    "Please attach the active license copy in the report, as the one on the report is expired.",
    "It appears that the incorrect appraiser signature is included on the report. Please review and revise.",
    "Please revise the effective date of the report as it precedes the signature date.",
    "It appears to be a typo in the year of the effective date; please revise."
];

export const ADDENDUM_GENERAL_REVISION_PROMPTS = [
    "Please have the appropriate data noted under the inventory analysis on the 1004MC addendum of the report.",
    "Please have the appropriate data filled and checkboxes marked on the 1004mc addendum.",
    "Please include the 1004MC addendum in the report.",
    "Please comment on the subject's exposure time in the report.",
    "The photos indicate the subject’s bathroom count as 3; however, the sales grid, improvements section and sketch show the bathroom count as 2. Please revise.",
    "Comps 1-3 are on a supplemental value addendum, but it can be the regular URAR grid. The ARV just needs to be included on the supplemental value addendum.",
    "The sketch and photos indicate the subject’s bathroom count as 4; however, the sales grid and improvements section show the bathroom count as 3. Please revise.",
    "The sketch and photos indicate the subject’s bedroom count as 4; however, the sales grid and improvements section show the bedroom count as 3. Please revise.",
    "The sketch indicates the subject has a porch; however, the porch box is not marked in the Improvements section; please revise.",
    "Please crop/blur the human identity visible in the living area photo provided on page #20.",
    "Please label comp #4 on the location map.",
    "Please provide labels for the photos provided on pages #14-20.",
    "It appears the subject's bathroom photo is wrongly labeled as \"ABOVE GROUND POOL\" on page# 23, please revise.",
    "The subject’s bedroom 2 & 3 photo is wrongly labeled as bathroom 2 & 3 on page# 16, please revise.",
    "Please provide labels for the last 2 photos of page #20.",
    "The ‘subject to proximity’ of all comps mentioned in the sales grid does not match with the location map; please revise.",
    "Please have the ‘Proximity to subject’ noted for all comps on the rental grid and sales grid.",
    "Please remove the additional comp #8 from the location map.",
    "Adjusted values of all comps noted on page #08 do not match with the sales grid; please revise.",
    "Please correct the addresses on the location map so they correspond with the sales grid.",
    "Please correct the addresses of comps# 4 and 5 on the location map so they correspond with the sales grid and remove the additional comps from the location map.",
    "Please revise the subject’s address on the aerial map.",
    "Please have the appropriate checkbox marked for ‘Total # of Comparable Sales (Settled)’ under the overall trend on the 1004MC addendum of the report.",
    "The Sketch needs to line up with the photos. On the sketch - Currently there is a 1/2 bath listed in Unit B but per the photos that is in the other unit. There is a Den in unit b on the sketch but appears to be in unit A per the photos. There is a photo for a dining room for unit A but no listed on the sketch. Please address.",
    "Please have the appropriate data noted for ‘Total # of Comparable Sales (Settled)’ inventory analysis on 1004MC addendum of the report.",
    "All basement photos are labeled 'Basement'. Please include the individual room labels, as well.",
    "Basement photos must include the basement label, please revise the label of basement photos accordingly.",
    "Please include \"Basement\" in the labels of the appropriate basement photos.",
    "Please attach a copy of the appraiser's invoice to the report.",
    "Please remove the invoice from the report.",
    "Please remove the blank page #12 from the report.",
    "Please also revise the label of the basement family room to basement bedroom in the photo addendum.",
    "ADU photos must include the ADU label; please revise the label of ADU photos accordingly.",
    "1004MC addendum: The question 'Are foreclosure sales (REO sales) a factor in the market?' is marked as YES; however, the description is not provided. Please provide it.",
    "Please address if there are security bars on bedroom windows and if there are safety release latches.",
    "Photos and sketch show the subject has 1 bathroom in the basement; however, the same is not reflected in the sales grid; please revise.",
    "Some photos on page #21 are missing the labels; please provide it.",
    "One of the photo on page #21 is missing the label; please provide it.",
    "1004MC addendum: Please have the appropriate data filled under ‘Subject Project Data’ of the CONDO/CO-OP PROJECTS section.",
    "Please revise the address of comps #2-7 on the location map to match the sales grid and remove the additional comps #8 and 9 from the location map.",
    "Please have the appropriate checkbox marked for ‘Seller (developer, builder, etc.) paid financial assistance prevalent?’ under the overall trend on the 1004MC addendum of the report.",
    "Please revise the conflicting comment noted on page #12, which reads, “An adjustment was made to Comparable 4 for the percentage of list price to sales price for the neighborhood.”.",
    "The comment on page #14 reads, “Subject gross living area is 1915 sq ft”; however, the sketch, improvement section, and sales grid indicate GLA as 1812 sq ft. Please revise.",
    "The comment on page #18 reads, “This appraisal is made subject to repair of the damaged window”; however, the checkbox in the reconciliation section is marked as As-is. Please revise.",
    "The bed/bath adjustment made for all comps seems to be inconsistent with the comments noted on page #20; please revise.",
    "Please confirm if smoke/CO detectors are installed.",
    "Please confirm if smoke/CO detectors are installed and include photos.",
    "The appraiser is to indicate at the beginning of the Additional Features field that the “measurement complies with the ANSI standard.”. If the appraiser is unable to adhere to the ANSI Z765-2021 standard, they must enter \"GXX001-\" at the beginning of the Additional Features field of the appraisal and provide an explanation of why they were not able to comply.”",
    "Please indicate if the hot water heater is properly double strapped (earthquake straps).",
    "Please comment on the appraiser's fee in the report: $200.00",
    "Please comment on the AMC fee in the report: $",
    "Please comment on the AMC registration # in the report. 2019007666",
    "Please comment on the AMC license expiration date in the report.",
    "Please comment on the AMC registration #558000312 in the report along with the expiration date 12/31/2025.",
    "Please revise the checkboxes marked under ‘Overall Trend’; only one box should be marked for each line.",
    "Please include the below statement in the report:\nI have/have NOT performed services, as an appraiser or in any other capacity, regarding the property that is the subject of this report within the three-year period immediately preceding acceptance of this assignment.",
    "Please have the appropriate information filled and checkboxes marked on the USPAP addendum of the report.",
    "Please have the checkbox marked for ‘I have/have NOT performed services…’ on the USPAP addendum.",
    "Should the shed be attributed any value? Please comment.",
    "The sales grid shows only 6 comps; however, the location map and photo show 7 comps. Please revise.",
    "IL State: Please include the following statement in the report: The comments by the licensed real estate appraiser contained within this appraisal report on the condition of the property do not address \"standards of practice\" as defined in the Home Inspector License Act [225 ILCS 441] and 68 Ill. Adm. Code 1410 and are not to be considered a home inspection or home inspection report.",
    "There is a blank page that is labeled \"Plat Map.\" Please include the plat map or remove the page.",
    "There is a blank photo that is labeled \"Alternate Street Scene\" and \"112 Maddoxwoods Dr.\" Please include the photo or remove the label.",
    "The same photo is provided twice but is labeled as \"Dining\" and \"Bedroom.\" Please revise accordingly.",
    "For Plaza mortgage only: Can the appraiser please remove the invoice from the report? This will be delivered to the client as a separate document.",
    "Please remove the W-9 from the report.",
    "Sketch calculation summary: The subject’s GLA is noted under Non-Living Area; please revise.",
    "The address on comp #5 has been partially cut off on the location map; please revise.",
    "Comp #3's address on the location map is overlapped by the subject address; please revise.",
    "For Plaza mortgage only: Please upload the appraiser's invoice into the supporting documents.",
    "The subject has a basement kitchen. Is this permitted? Are there any health and safety issues? Please address if there is any effect on marketability/value.",
    "The subject has a second kitchen. Is this permitted? Are there any health and safety issues? Please address if there is any effect on marketability/value.",
    "Please label the family room on the sketch as per the photos.",
    "Please provide the family room photo in the report per the sketch.",
    "Please provide an aerial map in the report.",
    "Please provide all the comps photos in the report.",
    "The comment on page #10 reads, “GLA is adjusted at $80.00 per square foot. ”; however, the GLA is adjusted at $65/SF in the sales grid; please revise to match.",
    "There appears to be a formatting error in the report provided, as all of the text is overlapping and illegible. The sales grid is also blank. Please review and revise.",
    "Please provide an updated signature date in the report.",
    "Please rotate the license copy provided in the report as it's upside down.",
    "Please address the use of Comp 2 that was sold 4 years ago, or correct the dates if it was a typo.",
    "Photos indicate the subject has aSump Pump’ ; however, the Sump Pump box is not marked in the Improvements section; please revise.",
    "Please revisit the labeling of the subject’s interior photos provided on page #14, as some photos have wrong labels and some photos are missing the labels.",
    "On page #17: The photo labeled as ‘U2 Bed’ does not match with its appearance; please revise or comment.",
    "It appears the 4th rental comp photo was included as \"Sold Comp 5.\" Please revise and include the photo as the 4th photo for the \"Rental Comp\" photo addendum.",
    "Supplemental addendum pages are cut off on the right. Provide corrected addendums with all information included.",
    "Unit Interchanged: 1. Sales grid reflects 1 bedroom for unit #1, but photos reflect 2. Please revise. 2. Sales grid reflects 2 bedroom for unit #3, but photos reflect 1. Please revise."
];

export const FORM_1007_REVISION_PROMPTS = [
    "Please have the 1007 form included in the report.",
    "Please revise the subject's Date Lease Begins to 05/01/2024 and Date Lease Expires to 04/30/2025 per the lease agreement on the 1007 form.",
    "Please provide all rental comps photos in the report.",
    "Please include the rental comparables on the location map.",
    "The occupancy is marked as owner; however, the 1007 form says vacant. Please verify.",
    "Please revise the ‘Date Lease Expires’ noted for rental comp #1 on the 1007 form as its ‘Date Lease Expires’ is prior to its ‘Date Lease Begins.’.",
    "Please revise the ‘Date Lease Expires’ noted for rental comp #1 on the 1007 form as its ‘Date Lease Expires’ is the same as its ‘Date Lease Begins.’.",
    "The opinion of market rent is not bracketed by the adjusted rent price of rental comps.",
    "Please have the opinion of market rent noted on the 1007 form.",
    "Please revise the ‘Date Lease Expires’ noted for the subject in the rental grid as it is the same as its ‘Date Lease Begins.’",
    "The GLA adjustments made on the 1007 form appear to be excessive; please revise.",
    "Please review the GLA adjustments made on the 1007 form, as they appear to be excessive. Also, the opinion of market rent is not bracketed by the adjusted rent price of rental comps.",
    "Please have the ‘Date Lease Begins’ and ‘Date Lease Expires’ noted for all rental comps on the rental grid.",
    "Please have the ‘Date Lease Begins’ and ‘Date Lease Expires’ noted for rental comp #3 on the rental grid.",
    "The occupancy is marked as Owner; however, the photos indicate it is vacant, and the 1007 form shows it is currently rented. Please verify/revise.",
    "Please attach the 1007 to the original report and upload. The 1007 does not need to be separately uploaded.",
    "Please have the 'Proximity to Subject' noted for all rental comps on the 1007 form.",
    "Per assignment instructions, at least 3 rental comps must be needed to develop the market rent, please provide one more rental comp in the report.",
    "Are the addendum pages able to be updated with the borrower name, subject address, and client name/address?",
    "The subject cannot be used as a rental comp. Please find an alternate comp to develop market rent.",
    "The subject cannot be used as one of the first 3 comps in the grid. Please replace or reorder the comps accordingly.",
    "Rental comps #2 and 3 appear to be long-term rentals; however, their lease date is noted as “Per Night.” Please revise.",
    "Market rent comes out to $16,000; however, the current rent is noted as $30,000. Please advise.",
    "Please have the lease dates noted for all rental comps on the 1007 form.",
    "The occupancy is marked as owner/vacant; however, the subject’s lease dates and current rent are provided on the 1007 form. Please verify.",
    "The subject is in rent control; however, all comps used in the report are not in rent control. Please provide a similar comp to the subject or comment as to why none could be provided.",
    "Rental comps 1 and 2 lease dates reflect 'vacant.'. Please note that only active leases can be considered for market rent. Please provide comps with active leases or revise as needed.",
    "Subject rent schedule section: Under ‘Opinion Of Market Rent’ for unit #1, the unfurnished rent is not the same as its total rent; please revise.",
    "All rental comps lease dates are noted as ‘Active Listing’. Please utilize a minimum of 3 closed rentals to develop market rent. Please expand search parameters for distance, if needed.",
    "Location map is not clear/illegible. Please provide a clear copy of the location map.",
    "MLS photo for comp #2 is not clear. It appears the photo is corrupted or was not properly uploaded to the appraisal. Please review and revise.",
    "The comments in the Supplemental Addendum appear to be partially cut off due to a formatting error. Please review and revise.",
    "For the rent schedule, the order was placed for short-term rentals Please utilize short-term rentals to develop market rent.",
    "Annual rentals have been provided on the rent schedule; however, the assignment is for short-term market rent. Please produce market rent utilizing short-term rentals.",
    "Regarding below revision, only VRBO pages has been uploaded instead of 1007 form, please advise: 1. Please provide a full color for the VRBO portion"
];